### ISSUE TITLE
Cannot build: camera_device_open() - too many arguments

### ISSUE THREAD

**Issue by edoardogiacomello** [intel/icamerasrc#32]
Hello, 
I'm trying to build icamerasrc to make the webcam of my Lenovo X1 Carbon (gen 10) work in Ubuntu 22.04.
I've installed all the other dependencies listed in the instructions with no errors (using ipu6ep), however then when i run 
`make -j8` the build fails with this error:

```
gstcamerasrc.cpp: In function ‘gboolean gst_camerasrc_start(GstCamBaseSrc*)’:
gstcamerasrc.cpp:2839:27: error: too many arguments to function ‘int icamera::camera_device_open(int)’
 2839 |   ret = camera_device_open(camerasrc->device_id, camerasrc->num_vc);
      |         ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gstcamerasrc.cpp:62:
/usr/include/libcamhal/api/ICamera.h:210:5: note: declared here
  210 | int camera_device_open(int camera_id);
      |     ^~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:623: libgsticamerasrc_la-gstcamerasrc.lo] Error 1
make[3]: Leaving directory '<redacted>/icamerasrc/src'
make[2]: *** [Makefile:684: all-recursive] Error 1
make[2]: Leaving directory '<redacted>/icamerasrc/src'
make[1]: *** [Makefile:519: all-recursive] Error 1
make[1]: Leaving directory '<redacted>/icamerasrc'
make: *** [Makefile:428: all] Error 2
```

Am I doing something wrong or is it just a bug?

Thanks,
E.

**Comment by gfarrell** [comment]
I have this too on archlinux -- attempting to install gives me the exact same output as above.

**Comment by brmarkus** [comment]
For the engineering-team to have a chance to look into this, can you provide as many information, please?
Which versions (name, branch, repo, commit) of which components of icamerasrc and its dependencies do you have installed (and how)?
How does your environment (HW and SW) look like?
How have you set-up your build environment, compiling "natively" or e.g. within a Docker container (or virtual-env)?
Any local changes to source-code?
Is this the first time you tried to build - or have you seen it building successfully using an older version or other HW?

**Comment by HackXIt** [comment]
I changed the line that is mentioned in the output of make to
```c
//ret = camera_device_open(camerasrc->device_id, camerasrc->num_vc);
    ret = camera_device_open(camerasrc->device_id);
```

It then was able to compile, but I'm unsure if this will break something else further down the line.

Also it still doesn't work for me, because when running `sudo -E gst-launch-1.0 icamerasrc buffer-count=7 ! video/x-raw,format=YUY2,width=1280,height=720 ! videoconvert ! ximagesink` I get this output:
```
WARNING: erroneous pipeline: no element "icamerasrc"
```

I'm not sure what is going wrong here, but according to https://aur.archlinux.org/packages/icamerasrc-git I'm not alone with the problem.

I'm unsure on how to proceed, since I'm new to this type of scenario.

But generally I followed the guides of the ipu6 projects in order and everything worked up to the point of trying to compile this plugin.

**Comment by brmarkus** [comment]
@HackXIt do you respond to @edoardogiacomello ?

In this case the IPU-camera-HAL version doesn't match to the used version of icamerasrc.

(Optional) Support for e.g. virtual-channels was considered in IPU6-Camera-HAL branch "iotg_ipu6", see e.g. here: "https://github.com/intel/ipu6-camera-hal/blob/iotg_ipu6/include/api/ICamera.h#L237".

Unfortunately I don't see a public documentation of what dependency in which version/branch/commit/release to use.

**Comment by chdietrich** [comment]
> WARNING: erroneous pipeline: no element "icamerasrc"

Solved this by using 17841ab6249aaa69bd9b3959262bf182dee74111

Lenovo Thinkpad X1 Carbon G10
Ubuntu 22.04.2 x64
ipu6-drivers / master / dfedab03f3856010d37968cb384696038c73c984
ivsc-driver / main / c8db12b907e2e455d4d5586e5812d1ae0eebd571
ipu6-camera-hal / main / 884b81aae0ea19a974eb8ccdaeef93038136bdd4
ipu6-camera-bins / main / 276859fc6de83918a32727d676985ec40f31af2b
icamerasrc / icamerasrc_slim_api / 17841ab6249aaa69bd9b3959262bf182dee74111

sudo -E gst-launch-1.0 icamerasrc buffer-count=7 device-name=ov2740-uf ! video/x-raw,format=NV12,width=1280,height=720 ! videoconvert ! ximagesink

**Comment by almereyda** [comment]
The internal refactoring as documented in the discussion at https://github.com/intel/icamerasrc/pull/31#discussion_r1184456155 still appears to be going on: The suggestion to checkout the tag `20230307_0904_rpl_plat` does not result in this error to go away.

Did anyone have success in compiling `icamerasrc` against the current other ipu6 projects?
